# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomadation',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='canoccupy',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pronearea',
            name='population',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='humanaid',
            field=models.IntegerField(null=True),
        ),
    ]
