# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-21 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170212_0900'),
    ]

    operations = [
        migrations.AddField(
            model_name='accomadation',
            name='loyalto',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='loyalto',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='pronearea',
            name='loyalto',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='loyalto',
            field=models.CharField(max_length=70, null=True),
        ),
    ]
