# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-28 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20170221_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomadation',
            name='loyalto',
            field=models.CharField(default='nil', max_length=70),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='loyalto',
            field=models.CharField(default='nil', max_length=70),
        ),
        migrations.AlterField(
            model_name='pronearea',
            name='loyalto',
            field=models.CharField(default='nil', max_length=70),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='loyalto',
            field=models.CharField(default='nil', max_length=70),
        ),
    ]
