# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-17 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20170228_1339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomadation',
            name='capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='canoccupy',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pronearea',
            name='population',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='humanaid',
            field=models.IntegerField(default=0),
        ),
    ]
