# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstaid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kit', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='updates_firstaid', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packet', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='updates_food', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fireengine', models.IntegerField(null=True)),
                ('jcb', models.IntegerField(null=True)),
                ('ambulance', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='updates_machine', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Messagebox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromaddr', models.CharField(max_length=70)),
                ('toaddr', models.CharField(max_length=70)),
                ('topic', models.CharField(max_length=70)),
                ('message', models.CharField(max_length=500)),
                ('ack', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rescuetool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('box', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='updates_rescuetool', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('veh_type', models.CharField(max_length=70)),
                ('capacity', models.IntegerField(null=True)),
                ('user', models.ManyToManyField(related_name='updates_transport', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='updates_water', to='home.User')),
            ],
        ),
    ]
