# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlunit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagebox',
            name='nack',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='parameter',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='messagebox',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
