# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-19 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
        ('controlunit', '0002_auto_20170214_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportGoods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='updates_transportg', to='home.User')),
            ],
        ),
        migrations.CreateModel(
            name='TransportHuman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='updates_transporth', to='home.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='transport',
            name='user',
        ),
        migrations.DeleteModel(
            name='Transport',
        ),
    ]
